### ISSUE TITLE
RTEi comments on Antares v8.3.0-rc1

### ISSUE THREAD

**Issue by Milos-RTEi** [rte-i/Antares_Simulator#51]
1. There is a line missing between 64-65. Probably merge problem. Miraculously, I don't even understand how it provides proper results. 
https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/a5f6f8e22cd14b1037e7e15003849295b0869c56/src/solver/optimisation/adequacy_patch.cpp#L58-L70
2. I think we agreed that from version 8.3 ini file for each area is mandatory. So this line should say >=830 and "&& study.parameters.include.adequacyPatch" should be deleted. If it stays like this area-ini files are not read at all when opening the network if study.parameters.include.adequacyPatch = false (Enable Adequacy Patch ui option is set to false), so the user loses all the info about area adequacy patch mode.
https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/a5f6f8e22cd14b1037e7e15003849295b0869c56/src/libs/antares/study/area/list.cpp#L756
3. Some of the RTEi implementation of the RTE comments are not present in the RTE/develop branch. 
Like: 
names SetToZero12LinksForAdequacyPatch/SetToZero11LinksForAdequacyPatch are replaced with setToZeroNTCfromOutToIn_AdqPatch/setToZeroNTCfromOutToOut_AdqPatch.
https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/a5f6f8e22cd14b1037e7e15003849295b0869c56/src/solver/optimisation/adequacy_patch.cpp#L74-L75
functions setBoundsAdqPatch and setBoundsNoAdqPatch are replaced with one call setNTCbounds.
https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/a5f6f8e22cd14b1037e7e15003849295b0869c56/src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp#L159-L163
etc...
While merging RTE/develop branch into RTEi/adq-patch branch we kept RTEi implementation!

**Comment by Milos-RTEi** [comment]
Hi @hugo-antoine-rtei. I have some comments on Antares v8.3.0-rc1. 
Take a look and we can discuss if necessary. If you agree with them we can then forward to RTE.

**Comment by flomnes** [comment]
Hi @Milos-RTEi,
1. There is no missing line
```cpp
switch(x) {
case 1:
case 2:
   return 1;
}
```
is equivalent to
```cpp
switch(x) {
case 1:
   return 1;
case 2:
   return 1;
}
```
2. I agree, we should always try to read file `adequacy_patch.ini`. If the read fails (for example because we have a 8.2 study), no error should be issued : just use the default values instead.
3. We applied some remarks ourselves, cherry-picked some of your commits, so you may find a few conflicts. Sorry about that.

**Comment by Milos-RTEi** [comment]
Hi @flomnes, thanks for the reply!
